- name: cart setup
  hosts: cart
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
     name: nodejs
     state: present
    
  - name: roboshop user create
    ansible.builtin.user:
     name: roboshop
     comment: roboshop system user
     system: yes
     shell: /sbin/nologin
     home: /app

  - name: remove app directory
    ansible.builtin.file:
     path: /app
     state: absent

  - name: create app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: remove app from tmp directory
    ansible.builtin.file:
     path: /tmp/cart.zip
     state: absent

  - name: download cart application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
     dest: /tmp/cart.zip

  - name: extract cart application to app directory
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes

  - name: install dependencies
    community.general.npm:
     path: /app

  - name: copy service file
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service

  - name: Start cart service
    ansible.builtin.service:
     name: cart
     state: started
     enabled: yes

  - name: daemon-reload
    ansible.builtin.systemd_service:
     name: cart
     state: restarted
     enabled: yes
     daemon-reload: yes

